import assert from 'node:assert/strict'
import { chartSegments, formatMetric } from '../src/features/monitoring/model.js'
const points = [0, 1, null, 0, 3].map((value, i) => ({ timestamp: 60 * i, values: { cpu: value } }))
const chart = chartSegments(points, 'cpu', 60)
assert.equal(chart.segments.length, 2)
assert.deepEqual(chart.segments.map(segment => segment.length), [2, 2])
assert.equal(chart.segments[0][0].y, 180, 'zero must remain a valid observed point')
assert.equal(chartSegments([{timestamp: 0, values: {cpu: 1}}, {timestamp: 180, values: {cpu: 2}}], 'cpu', 60).segments.length, 2)
assert.equal(chartSegments(points, 'missing', 60).segments.length, 0)
assert.equal(chartSegments(points, 'cpu', null).segments.length, 4)
assert.equal(formatMetric(null, '%'), '관찰 없음')
assert.equal(formatMetric(NaN, 'bytes'), '관찰 없음')
assert.equal(formatMetric(0, '%'), '0.0%')
assert.equal(formatMetric(1024, 'bytes/s'), '1.0 KiB/s')
assert.equal(formatMetric(0.5, 'bytes/s'), '0.5 B/s')
console.log('monitoring chart gaps, missing values, rates and units exercised')
const percentChart = chartSegments(points, 'cpu', 60, 100)
assert.equal(percentChart.maximum, 100, 'CPU chart must not stretch low activity into apparent saturation')
assert.equal(percentChart.segments[0][1].y, 178.4)
const { metricsTargetMatches } = await import('../src/features/monitoring/model.js')
const report = {target: {kind: 'vm', node_id: 'node-a', vmid: 7001}, timeframe: 'hour'}
assert.equal(metricsTargetMatches(report, 'vm', 'node-a', '7001', 'hour'), true)
assert.equal(metricsTargetMatches(report, 'vm', 'node-b', '7001', 'hour'), false)
assert.equal(metricsTargetMatches(report, 'vm', 'node-a', '7002', 'hour'), false)
assert.equal(metricsTargetMatches(report, 'vm', 'node-a', '7001', 'day'), false)
assert.equal(metricsTargetMatches(report, 'node', 'node-a', '', 'hour'), false)
assert.equal(metricsTargetMatches(null, 'node', 'node-a', '', 'hour'), false)
